[package]
name = "sphere-knn"
edition = "2021"
keywords = ["knn"]
license = "MIT"
repository = "https://github.com/nrakochy/sphere-knn"
version = "0.1.0"

[dependencies]
serde = "1.0.192"
positionable = { path = "../positionable", version = "0.1.0" }
